baseURL = "https://djelky.pilato.fr/"
languageCode = "en"
title = "DJ Elky | Feel the Groove with Funk &amp; House mixes 🎧"
theme = "podcast4deejays"
# Allows emojis in markdown
enableEmoji = true
# Allows git info to be extracted
enableGitInfo = true

[mediaTypes]
  [mediaTypes."text/xml"]
    suffixes = ["rss"]

[outputFormats]
  [outputFormats.RSS]
    baseName = "djelky"
    mediaType = "text/xml"
    isHTML = false
    isPlainText = true
    noUgly = true

[outputs]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  page     = ["HTML"]
  taxonomy = ["HTML"]
  term     = ["HTML"]

[taxonomies]
  keyword = "keywords"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Footer configuration
  siteStartYear = 2011
  themeName = "podcast4deejays"
  themeLink = "https://github.com/lyquocphong/hugo-theme-djelky"
  # Image for social media sharing (OpenGraph / Twitter Cards)
  # Dimensions should be 1200x630px for best results
  image       = "img/dj-elky-small.jpg"
  # Default description for social sharing (used if no description in front-matter)
  # description = "If you love funk, house and DJ groove sound, you will like those mixes. Enjoy!"
  # Optional: title for social media sharing (if not set, Site.title is used)
  # title       = "Custom title for social media"
  twitter     = "@dadoonet"

[params.podcast]
  # Podcast Name, which is normally the DJ Name
  name         = "DJ Elky"
  # Podcast Title (if not set, this is the Site title)
  # title        = "DJ Elky | Feel the Groove with Best Funk &amp; House Music Mixes 🎧"
  # Podcast Author
  real_name    = "David Pilato"
  author       = "DJ Elky"
  email        = "david@pilato.fr"
  cover        = "img/authors/dj-elky.png"
  # Podcast ID and description
  # Unique id: It's computed from dj.pilato.fr using https://www.uuidtools.com/v5
  podcastGUID  = "5e560267-5f32-55d3-b370-8f66f80ddb8f"
  subtitle     = "Just playing with my DJ gears, from Hercules DJ Console, DDJ-T1 to DJM-V10-LF and CDJ-3000"
  description  = "Love funk, house, and DJ groove sounds? Dive into DJ Elky's exclusive mixes! High-energy vibes curated for your listening pleasure. Enjoy the beat! 🔥"
  filename     = "djelky.rss"
  # For the website only, it adds a link to the podcast
  podcastLink   = "https://podcasts.apple.com/fr/podcast/dj-elky-mixes/id959495351"
  spotifyLink   = "https://open.spotify.com/show/5u5Xgmixz6wLVl9srgACom"
  # For each episode
  # If the page does not define an audio_url field, the mp3 file is automatically guessed
  # from the website path with baseAudioURL as a prefix
  baseAudioURL = "https://storage.googleapis.com/djdadoo/"
  # This is a prefix for every episode in the RSS generated file
  trackTitle   = "David's Mix"
  # Optional keywords which are appended automatically to any other keyword defined for the episode
  keywords     = ["DJ Elky", "Mix"]
  # Default audio type when audio_type is not set for the episode
  audioType    = "audio/mpeg"
