name = "podcast4deejays"
license = "Apache2"
description = "Theme for Deejays who are willing to share their mixes as podcasts"
homepage = "https://djelky.pilato.fr"
min_version = "0.157.0"

[author]
  name = "David Pilato"
